# Generated by sila2.code_generator; sila2.__version__: 0.10.1
from __future__ import annotations

from queue import Empty, Queue
from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.cancelcontroller import (
    UUID,
    CancelAll_Responses,
    CancelCommand_Responses,
    CancelControllerBase,
)

if TYPE_CHECKING:
    from ..server import Server


class CancelControllerImpl(CancelControllerBase):
    registeredCBs: list[Queue]

    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        CancelControllerImpl.registeredCBs = []

    def CancelCommand(
        self, CommandExecutionUUID: UUID, *, metadata: MetadataDict
    ) -> CancelCommand_Responses:
        raise NotImplementedError  # TODO

    def CancelAll(self, *, metadata: MetadataDict) -> CancelAll_Responses:
        for cb in self.registeredCBs:
            if cb.empty():
                cb.put(True)
        return CancelAll_Responses()
