# Generated by sila2.code_generator; sila2.__version__: 0.10.1
from __future__ import annotations

from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.settingsservice import SetSerialPort_Responses, SettingsServiceBase

if TYPE_CHECKING:
    from ..server import Server


class SettingsServiceImpl(SettingsServiceBase):
    PortName: str = None

    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

    def get_SerialPort(self, *, metadata: MetadataDict) -> str:
        return SettingsServiceImpl.PortName

    def SetSerialPort(
        self, PortName: str, *, metadata: MetadataDict
    ) -> SetSerialPort_Responses:
        SettingsServiceImpl.PortName = PortName
