# Generated by sila2.code_generator; sila2.__version__: 0.10.1
from __future__ import annotations

import logging
from queue import Queue
from time import sleep, time
from typing import TYPE_CHECKING

from sila2.framework.errors.undefined_execution_error import UndefinedExecutionError
from sila2.framework.errors.validation_error import ValidationError
from sila2.server import (
    MetadataDict,
    ObservableCommandInstanceWithIntermediateResponses,
)

from ..api.teleshake import FrameError, InternalError, ParameterError, Teleshake1536
from ..feature_implementations.cancelcontroller_impl import CancelControllerImpl
from ..feature_implementations.settingsservice_impl import SettingsServiceImpl
from ..feature_implementations.simulationcontroller_impl import SimulationControllerImpl
from ..generated.shakecontroller import (
    GoHome_Responses,
    LockPlate_Responses,
    ShakeControllerBase,
    ShakeForTime_IntermediateResponses,
    ShakeForTime_Responses,
    StartShaking_Responses,
    StopShaking_Responses,
    UnlockPlate_Responses,
)
from ..generated.shakecontroller.shakecontroller_errors import CancelledError
from ..generated.shakecontroller.shakecontroller_errors import (
    TimeoutError as TimeoutErr,
)

if TYPE_CHECKING:
    from ..server import Server

logger = logging.getLogger(__name__)


class ShakeControllerImpl(ShakeControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self.cancelEvent = Queue()
        CancelControllerImpl.registeredCBs.append(self.cancelEvent)

    def _CreateShakerInstance(self):
        if not self._IsSimulationActive():
            return Teleshake1536(port=self._GetPort())

        class Dummy:
            def __enter__(self):
                return self

            def __exit__(self, *args):
                pass

            def CloseClamp(self, addr: int = 0):
                pass

            def OpenClamp(self, addr: int = 0):
                pass

            def SetRPM(self, rpm, addr: int = 0):
                pass

            def SetPower(self, power, addr: int = 0):
                pass

            def StartDevice(self, addr: int = 0):
                pass

            def StopDevice(self, addr: int = 0):
                pass

        return Dummy()

    def _GetPort(self):
        return SettingsServiceImpl.PortName

    def _IsSimulationActive(self):
        return SimulationControllerImpl.SimulationActive

    def StopShaking(
        self, *, shakerId: int, metadata: MetadataDict
    ) -> StopShaking_Responses:
        try:
            with self._CreateShakerInstance() as shaker:
                shaker.StopDevice(addr=shakerId)
        except TimeoutError as ex:
            logger.exception(ex)
            raise TimeoutErr(repr(ex))
        except (FrameError, IOError, InternalError) as ex:
            logger.exception(ex)
            raise UndefinedExecutionError(repr(ex))
        except ParameterError as ex:
            logger.exception(ex)
            raise ValidationError(repr(ex))
        return StartShaking_Responses()

    def StartShaking(
        self,
        shakerId: int,
        TargetSpeed: float,
        TargetPower: float,
        *,
        metadata: MetadataDict,
    ) -> StartShaking_Responses:
        try:
            with self._CreateShakerInstance() as shaker:
                shaker.SetRPM(TargetSpeed, addr=shakerId)
                shaker.SetPower(TargetPower / 100, addr=shakerId)
                shaker.StartDevice(addr=shakerId)
        except TimeoutError as ex:
            logger.exception(ex)
            raise TimeoutErr(repr(ex))
        except (FrameError, IOError, InternalError) as ex:
            logger.exception(ex)
            raise UndefinedExecutionError(repr(ex))
        except ParameterError as ex:
            logger.exception(ex)
            raise ValidationError(repr(ex))
        return StartShaking_Responses()

    def GoHome(self, *, shakerId: int, metadata: MetadataDict) -> GoHome_Responses:
        return GoHome_Responses()

    def UnlockPlate(
        self, *, shakerId: int, metadata: MetadataDict
    ) -> UnlockPlate_Responses:
        try:
            with self._CreateShakerInstance() as shaker:
                shaker.OpenClamp(addr=shakerId)
        except TimeoutError as ex:
            logger.exception(ex)
            raise TimeoutErr(repr(ex))
        except (FrameError, IOError, InternalError) as ex:
            logger.exception(ex)
            raise UndefinedExecutionError(repr(ex))
        except ParameterError as ex:
            logger.exception(ex)
            raise ValidationError(repr(ex))
        return UnlockPlate_Responses()

    def LockPlate(
        self, *, shakerId: int, metadata: MetadataDict
    ) -> LockPlate_Responses:
        try:
            with self._CreateShakerInstance() as shaker:
                shaker.CloseClamp(addr=shakerId)
        except TimeoutError as ex:
            logger.exception(ex)
            raise TimeoutErr(repr(ex))
        except (FrameError, IOError, InternalError) as ex:
            logger.exception(ex)
            raise UndefinedExecutionError(repr(ex))
        except ParameterError as ex:
            logger.exception(ex)
            raise ValidationError(repr(ex))
        return LockPlate_Responses()

    def ShakeForTime(
        self,
        ShakerId: int,
        Runtime: int,
        TargetSpeed: float,
        TargetPower: float,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[
            ShakeForTime_IntermediateResponses
        ],
    ) -> ShakeForTime_Responses:
        try:
            with self._CreateShakerInstance() as shaker:
                instance.begin_execution()  # set execution status from `waiting` to `running`
                shaker.SetRPM(TargetSpeed, addr=ShakerId)
                shaker.SetPower(TargetPower / 100, addr=ShakerId)
                shaker.StartDevice(addr=ShakerId)

                while not self.cancelEvent.empty():  # Empty event queue
                    self.cancelEvent.get()

                def HandleCancel():
                    if not self.cancelEvent.empty():
                        shaker.StopDevice(addr=ShakerId)
                        raise CancelledError("Operation cancelled by user")

                start = time()
                passed_time = 0.0
                while passed_time < Runtime:
                    HandleCancel()
                    sleep(0.5)

                    passed_time = time() - start
                    time_left = Runtime - passed_time
                    if time_left < 0:
                        time_left = 0.0

                    instance.send_intermediate_response(
                        ShakeForTime_IntermediateResponses(time_left)
                    )

                shaker.StopDevice(addr=ShakerId)

        except TimeoutError as ex:
            logger.exception(ex)
            raise TimeoutErr(repr(ex))
        except (FrameError, IOError, InternalError) as ex:
            logger.exception(ex)
            raise UndefinedExecutionError(repr(ex))
        except ParameterError as ex:
            logger.exception(ex)
            raise ValidationError(repr(ex))

        return ShakeForTime_Responses()
