# Generated by sila2.code_generator; sila2.__version__: 0.10.1

from typing import Optional
from uuid import UUID

from sila2.server import SilaServer

from .feature_implementations.cancelcontroller_impl import CancelControllerImpl
from .feature_implementations.settingsservice_impl import SettingsServiceImpl
from .feature_implementations.shakecontroller_impl import ShakeControllerImpl
from .feature_implementations.simulationcontroller_impl import SimulationControllerImpl
from .generated.cancelcontroller import CancelControllerFeature
from .generated.settingsservice import SettingsServiceFeature
from .generated.shakecontroller import ShakeControllerFeature
from .generated.simulationcontroller import SimulationControllerFeature


class Server(SilaServer):
    def __init__(self, server_uuid: Optional[UUID] = None):
        # TODO: fill in your server information
        super().__init__(
            server_name="Teleshake1536Server",
            server_type="Teleshake1536Server",
            server_version="1.0",
            server_description="Teleshake 1536 Controller Server",
            server_vendor_url="https://www.novonordisk.com/",
            server_uuid=server_uuid,
        )

        self.cancelcontroller = CancelControllerImpl(self)
        self.set_feature_implementation(CancelControllerFeature, self.cancelcontroller)

        self.simulationcontroller = SimulationControllerImpl(self)
        self.set_feature_implementation(
            SimulationControllerFeature, self.simulationcontroller
        )

        self.settingsservice = SettingsServiceImpl(self)
        self.set_feature_implementation(SettingsServiceFeature, self.settingsservice)

        self.shakecontroller = ShakeControllerImpl(self)
        self.set_feature_implementation(ShakeControllerFeature, self.shakecontroller)
